### PR TITLE
Add a accept header to request to prevent blocking from waf devices

### PR DESCRIPTION
**Pull request by karmab**
Add a accept header to request to prevent blocking from waf devices ( for instance a mod_proxy with crs_21_protocol_anomalies rules loaded

### CODE REVIEW

**Comment by geemus** [comment]
Thanks for the patch, setting that as the default value for that header seems reasonable anyway and especially if it can help with the particular issues you are seeing. That said, I believe your patch would cause the accept value to always be `*/*`, even if the user tried to set it to something else. I think a similar approach that should get what you need would be to just add it to the list of default headers (in which case it will show up but can be over-ridden). Does that sound reasonable? It would mean moving the key/value to here: https://github.com/karmab/excon/blob/641594844255f7273b213523dfc09cf617fdb47d/lib/excon/constants.rb#L118

**Comment by karmab** [comment]
makes sense, so i did the change

**Comment by geemus** [comment]
Great. Looks like there is one test that specifically checks the values passed though, which is now breaking because it doesn't expect this value. Could you fix that?

The error can be seen here: https://travis-ci.org/excon/excon/jobs/195575311#L291
And I think the test to be fixed is here: https://github.com/excon/excon/blob/master/tests/middlewares/mock_tests.rb#L99

Thanks!

**Comment by geemus** [comment]
Pulling this in, will fix the test momentarily.

**Comment by geemus** [comment]
@karmab thanks! Sorry for the delay, had totally forgotten about this...

**Pull request merged**
