### PR TITLE
Use Ruby Resolv instead of LibC for hostname lookup

### PR DESCRIPTION
**Pull request by carlhoerberg**
This way DNS resolver can be replaced with:

```ruby
Resolv::DefaultResolver.replace_resolvers [Resolv::DNS.new(nameserver: '8.8.8.8')]
```

Related: #159, #184

### CODE REVIEW

**Comment by carlhoerberg** [comment]
Using this branch in production right now, polling a couple of thousand HTTPS APIs every minute or s for stats. Without it the DNS server would rate limit us and we couldn't swap it out as we had no access to modify /etc/resolve.conf.

**Review by geemus — APPROVED** [review]
Looks good, thanks!

**Comment by rafbm** [comment]
Anyone updating to Excon v0.80.0 for this functionality, beware of #747. Some versions of Resolv cause processes to hang in an infinite loop: https://bugs.ruby-lang.org/issues/17781.

**Comment by pboling** [comment]
Also: https://bugs.ruby-lang.org/issues/17748

**Comment by pboling** [comment]
My detailed fix for this issue:
https://github.com/mperham/sidekiq/issues/2175#issuecomment-841026801

**Pull request merged**
