### PR TITLE
Add missing require 'time'

### PR DESCRIPTION
**Pull request by voxik**
This fixes following errors:

```
$ rspec spec/requests/basic_spec.rb

... snip ...

Failures:

  1) Excon::Connection when an explicit uri is passed when nonblock is true and persistent is false when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
     Failure/Error: time = Time.parse(response.headers['Date'])

     NoMethodError:
       undefined method `parse' for Time:Class
     Shared Example Group: "a basic client" called from ./spec/requests/basic_spec.rb:38
     # ./spec/support/shared_examples/shared_example_for_clients.rb:40:in `block (8 levels) in <top (required)>'

  2) Excon::Connection when an explicit uri is passed when nonblock is true and persistent is true when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
     Failure/Error: time = Time.parse(response.headers['Date'])

     NoMethodError:
       undefined method `parse' for Time:Class
     Shared Example Group: "a basic client" called from ./spec/requests/basic_spec.rb:38
     # ./spec/support/shared_examples/shared_example_for_clients.rb:40:in `block (8 levels) in <top (required)>'

  3) Excon::Connection when an explicit uri is passed when nonblock is false and persistent is true when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
     Failure/Error: time = Time.parse(response.headers['Date'])

     NoMethodError:
       undefined method `parse' for Time:Class
     Shared Example Group: "a basic client" called from ./spec/requests/basic_spec.rb:38
     # ./spec/support/shared_examples/shared_example_for_clients.rb:40:in `block (8 levels) in <top (required)>'

  4) Excon::Connection when an explicit uri is passed when nonblock is false and persistent is false when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
     Failure/Error: time = Time.parse(response.headers['Date'])

     NoMethodError:
       undefined method `parse' for Time:Class
     Shared Example Group: "a basic client" called from ./spec/requests/basic_spec.rb:38
     # ./spec/support/shared_examples/shared_example_for_clients.rb:40:in `block (8 levels) in <top (required)>'

Finished in 2.02 seconds (files took 0.16142 seconds to load)
95 examples, 4 failures

Failed examples:

rspec ./spec/requests/basic_spec.rb[1:1:3:1:1:2:2:3] # Excon::Connection when an explicit uri is passed when nonblock is true and persistent is false when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
rspec ./spec/requests/basic_spec.rb[1:1:4:1:1:2:2:3] # Excon::Connection when an explicit uri is passed when nonblock is true and persistent is true when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
rspec ./spec/requests/basic_spec.rb[1:1:5:1:1:2:2:3] # Excon::Connection when an explicit uri is passed when nonblock is false and persistent is true when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
rspec ./spec/requests/basic_spec.rb[1:1:6:1:1:2:2:3] # Excon::Connection when an explicit uri is passed when nonblock is false and persistent is false when :method is get and :path is /content-length/100 #request Excon::Response#headers ['Date'] returns a valid date
```

### CODE REVIEW

**Comment by geemus** [comment]
Seems good, surprised I hadn't run into it (maybe a particular ruby version thing or something?).

**Comment by geemus** [comment]
Thanks!

**Comment by voxik** [comment]
I'd say that it depends how the test suite is executed. If you always execute entire test suite via Rake, there is a chance that something requires the 'time' prior this test is executed. At least this is my theory ;)

**Comment by geemus** [comment]
Good theory, that could definitely account for it.

**Comment by voxik** [comment]
BTW I am using this ruby:

```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

**Comment by starbelly** [comment]
Thank you!

**Pull request merged**
