### PR TITLE
was this the original intent?

### PR DESCRIPTION
**Pull request by KellyMahan**
line 250 raise error was undefined

### CODE REVIEW

**Comment by imajes** [comment]
@KellyMahan that's a really interesting catch. Honestly, it shouldn't have gotten into that branch -- and i didn't test for that. 

but, on a larger note, it's really interesting as to why you'd hit that *at all*. what did the error throw when you changed that line?

**Comment by KellyMahan** [comment]
third comment on https://github.com/excon/excon/issues/505

**Comment by imajes** [comment]
@KellyMahan ok, that's weird, that comment didn't show for me when i loaded it first...

Can you share your OpenSSL lib, binary, and client versions?

**Comment by KellyMahan** [comment]
osx with latest updates

$ which openssl
/usr/bin/openssl

$ openssl version
OpenSSL 0.9.8zd 8 Jan 2015

$ brew list openssl
/usr/local/Cellar/openssl/1.0.2/bin/openssl

not sure which one is actually in use

**Comment by imajes** [comment]
@KellyMahan: ``` puts OpenSSL::OPENSSL_VERSION```

**Comment by KellyMahan** [comment]
OpenSSL 1.0.1i 6 Aug 2014

**Comment by imajes** [comment]
@KellyMahan: that's vulnerable and out of date. You need to recompile ruby against the newer openssl (that which is in your brew cellar should be fine, if you recently ran brew update/upgrade). You'll want to run something like this, assuming you use ruby-build:

```RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/Cellar/openssl/1.0.2 rbenv install ...```

**Comment by imajes** [comment]
right now mine reports as ```OpenSSL 1.0.2a 19 Mar 2015```, which has a patch to fix the non blocking IO problem.

**Comment by KellyMahan** [comment]
upgrading openssl fixed the bug dragonfly. Thanks

**Comment by geemus** [comment]
Thanks! Also glad you got your setup fixed, but we'll also bring this in for completeness.

**Pull request merged**
