### PR TITLE
Refactor gemspec

### PR DESCRIPTION
**Pull request by djberg96**
The gemspec for excon looks like it's some junky autogenerated thing from years ago. This PR cleans it up. I can address some of these specifically:

* specification_version - You shouldn't be messing with this. It is automatically set.
* required_rubygems_version - You shouldn't care at this point.
* rubygems_version - Same.
* rubyforge_project - RubyForge is dead.
* date - Automatically set by Rubygems.
* require_paths - The 'lib' directory is automatically set by Rubygems.
* files - Just use `git ls-files` instead of listing them individually.

With this configuration I ran `gem build excon.gemspec`. The generated spec looks like so:

```
--- !ruby/object:Gem::Specification
name: excon
version: !ruby/object:Gem::Version
  version: 0.59.0
platform: ruby
authors:
- dpiddy (Dan Peterson)
- geemus (Wesley Beary)
- nextmat (Matt Sanders)
autorequire: 
bindir: bin
cert_chain: []
date: 2017-10-18 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: rspec
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 3.5.0
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 3.5.0
- !ruby/object:Gem::Dependency
  name: activesupport
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: delorean
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: eventmachine
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.0.4
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.0.4
- !ruby/object:Gem::Dependency
  name: open4
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: rake
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: rdoc
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: shindo
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: sinatra
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: sinatra-contrib
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
- !ruby/object:Gem::Dependency
  name: json
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.8.5
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.8.5
- !ruby/object:Gem::Dependency
  name: puma
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
description: EXtended http(s) CONnections
email: geemus@gmail.com
executables: []
extensions: []
extra_rdoc_files:
- README.md
- CONTRIBUTORS.md
- CONTRIBUTING.md
files:
- ".document"
- ".gitignore"
- ".rspec"
- ".travis.yml"
- CONTRIBUTING.md
- CONTRIBUTORS.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- Rakefile
- benchmarks/class_vs_lambda.rb
- benchmarks/concat_vs_insert.rb
- benchmarks/concat_vs_interpolate.rb
- benchmarks/cr_lf.rb
- benchmarks/downcase-eq-eq_vs_casecmp.rb
- benchmarks/excon.rb
- benchmarks/excon_vs.rb
- benchmarks/for_vs_array_each.rb
- benchmarks/for_vs_hash_each.rb
- benchmarks/has_key-vs-lookup.rb
- benchmarks/headers_case_sensitivity.rb
- benchmarks/headers_split_vs_match.rb
- benchmarks/implicit_block-vs-explicit_block.rb
- benchmarks/merging.rb
- benchmarks/single_vs_double_quotes.rb
- benchmarks/string_ranged_index.rb
- benchmarks/strip_newline.rb
- benchmarks/vs_stdlib.rb
- changelog.txt
- data/cacert.pem
- excon.gemspec
- lib/excon.rb
- lib/excon/connection.rb
- lib/excon/constants.rb
- lib/excon/error.rb
- lib/excon/extensions/uri.rb
- lib/excon/headers.rb
- lib/excon/middlewares/base.rb
- lib/excon/middlewares/capture_cookies.rb
- lib/excon/middlewares/decompress.rb
- lib/excon/middlewares/escape_path.rb
- lib/excon/middlewares/expects.rb
- lib/excon/middlewares/idempotent.rb
- lib/excon/middlewares/instrumentor.rb
- lib/excon/middlewares/mock.rb
- lib/excon/middlewares/redirect_follower.rb
- lib/excon/middlewares/response_parser.rb
- lib/excon/pretty_printer.rb
- lib/excon/response.rb
- lib/excon/socket.rb
- lib/excon/ssl_socket.rb
- lib/excon/standard_instrumentor.rb
- lib/excon/test/plugin/server/exec.rb
- lib/excon/test/plugin/server/puma.rb
- lib/excon/test/plugin/server/unicorn.rb
- lib/excon/test/plugin/server/webrick.rb
- lib/excon/test/server.rb
- lib/excon/unix_socket.rb
- lib/excon/utils.rb
- spec/excon/error_spec.rb
- spec/excon/test/server_spec.rb
- spec/excon_spec.rb
- spec/helpers/file_path_helpers.rb
- spec/requests/basic_spec.rb
- spec/requests/eof_requests_spec.rb
- spec/requests/unix_socket_spec.rb
- spec/spec_helper.rb
- spec/support/shared_contexts/test_server_context.rb
- spec/support/shared_examples/shared_example_for_clients.rb
- spec/support/shared_examples/shared_example_for_streaming_clients.rb
- spec/support/shared_examples/shared_example_for_test_servers.rb
- tests/authorization_header_tests.rb
- tests/bad_tests.rb
- tests/basic_tests.rb
- tests/complete_responses.rb
- tests/data/127.0.0.1.cert.crt
- tests/data/127.0.0.1.cert.key
- tests/data/excon.cert.crt
- tests/data/excon.cert.key
- tests/data/xs
- tests/error_tests.rb
- tests/header_tests.rb
- tests/middlewares/canned_response_tests.rb
- tests/middlewares/capture_cookies_tests.rb
- tests/middlewares/decompress_tests.rb
- tests/middlewares/escape_path_tests.rb
- tests/middlewares/idempotent_tests.rb
- tests/middlewares/instrumentation_tests.rb
- tests/middlewares/mock_tests.rb
- tests/middlewares/redirect_follower_tests.rb
- tests/pipeline_tests.rb
- tests/proxy_tests.rb
- tests/query_string_tests.rb
- tests/rackups/basic.rb
- tests/rackups/basic.ru
- tests/rackups/basic_auth.ru
- tests/rackups/deflater.ru
- tests/rackups/proxy.ru
- tests/rackups/query_string.ru
- tests/rackups/redirecting.ru
- tests/rackups/redirecting_with_cookie.ru
- tests/rackups/request_headers.ru
- tests/rackups/request_methods.ru
- tests/rackups/response_header.ru
- tests/rackups/ssl.ru
- tests/rackups/ssl_mismatched_cn.ru
- tests/rackups/ssl_verify_peer.ru
- tests/rackups/streaming.ru
- tests/rackups/thread_safety.ru
- tests/rackups/timeout.ru
- tests/rackups/webrick_patch.rb
- tests/request_headers_tests.rb
- tests/request_method_tests.rb
- tests/request_tests.rb
- tests/response_tests.rb
- tests/servers/bad.rb
- tests/servers/eof.rb
- tests/servers/error.rb
- tests/servers/good.rb
- tests/test_helper.rb
- tests/thread_safety_tests.rb
- tests/timeout_tests.rb
- tests/utils_tests.rb
homepage: https://github.com/excon/excon
licenses:
- MIT
metadata: {}
post_install_message: 
rdoc_options:
- "--charset=UTF-8"
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubyforge_project: 
rubygems_version: 2.6.14
signing_key: 
specification_version: 4
summary: speed, persistence, http(s)
test_files: []
```

### CODE REVIEW

**Comment by geemus** [comment]
You are correct that it was auto-generated. In fact I usually have used a rake task to update it, which I think would partially break with this change. I think the change is in the right direction, but could you look at making the appropriate changes in the rakefile for the release task also? (I think it should just be deleting some parts that update things that you have removed). Thanks!

**Comment by djberg96** [comment]
@geemus The only thing you would have to change is the version. You can even get around that by splitting out the `VERSION` constant into its own `version.rb` file, and then `require` that within the gemspec.

As for the rest of the Rakefile, I see a bunch of stuff in there that I'm not exactly sure how it's being used or why. I rarely do more than run tests or package the gem myself. If you want to get fancy you can use `Rake::PackageTask`.

**Comment by geemus** [comment]
Fair enough. We do actually split out the version already, here: https://github.com/excon/excon/blob/master/lib/excon/constants.rb#L4. Could you require/reference that in the gemspec for us and I'll bring this in and deal with any other changes as needed? Thanks!

**Comment by djberg96** [comment]
@geemus You're referencing other constants within your constants.rb file, e.g. Excon::Middleware::ResponseParser, so I'd have to either create dummy values or require more files.

I would ask that the VERSION be split out into its own file (version.rb) and we can refactor after that.

**Comment by geemus** [comment]
@djberg96 fair enough. I think I was just being a little set in my ways, thank you for your patience. I've split out `version.rb` for you. If you could refer to that in this GEMSPEC, I can deal with any other issues as needed. Thanks!

**Comment by djberg96** [comment]
@geemus Done!

**Comment by djberg96** [comment]
Hm, Travis seems upset by that `require_relative` for some reason.

**Comment by geemus** [comment]
There was an unrelated issue in how I did things that should now be fixed (I restarted and at least the 2.0+ tests seem to be passing). We might just do something like excon/excon: https://github.com/excon/excon/blob/master/lib/excon.rb#L2-L3 (kind of gross, but works).

**Comment by djberg96** [comment]
Oh, are you supporting earlier versions than 2.x? If so, then I'll have to modify it.

**Comment by geemus** [comment]
@djberg96 yeah, we've always supported the earlier stuff. And though we will probably want to stop doing so at some point, there hasn't been a particularly strong reason to force us to do so yet. If you could make that change, that would be great. Thanks!

**Comment by djberg96** [comment]
@geemus Should be fine now. The current failure is the persistent JRuby stuff.

**Comment by geemus** [comment]
Ug, that jruby. Maybe we should consider just moving it to allowed failures, since it seems to be pretty consistently flaky...

**Comment by geemus** [comment]
Thanks!

**Comment by djberg96** [comment]
@geemus I would just move it to allowed failures for now and circle back around later.

**Comment by geemus** [comment]
Good call, done here: https://github.com/excon/excon/commit/0770d183a575271d53e982c37979dd15dbe7e461 (probably should have just done so a while ago).

**Pull request merged**
