### PR TITLE
Initial version of Excon::Test::Server

### PR DESCRIPTION
**Pull request by starbelly**
- Added Excon::Test::Server
 - Added Excon::Test::Plugin::Server::Rackup
 - Added initial spec for Excon::Test::Server and Rackup plugin
 - Added rackup_path to spec_helper

### CODE REVIEW

**Comment by geemus** [comment]
Hey, to clarify, is this just setting up some of the existing stuff in rspec context or are there changes?

**Comment by starbelly** [comment]
No changes, just the continuation of the migration to rspec. I wanted to make sure you agreed with this approach, if you do, then the next step is to finish writing the plugins for unicorn, puma, and sinatra. Then, I'll actually begin porting the test units. Note that none of the code in the test units will change, just the structure. The final step will be moving the test data (rackups, middlewares, etc. ) to the spec directory.

**Comment by geemus** [comment]
Sorry for delay, was on vacation last week. I think this seems fine. Should we go ahead and merge or wait to bring it all in at once?

**Comment by starbelly** [comment]
Figured as much with it being the end of summer. Nah, let's merge this and then I'm going to write plugins for unicorn and sinatra and port the rackup tests first, I'll make a PR out of that. Then I'll do a PR for the unicorn tests, and then finally a PR for the sinatra tests.

**Comment by geemus** [comment]
Sounds good, thanks!

**Pull request merged**
