### PR TITLE
Run tests with ruby 2.3.3

### PR DESCRIPTION
**Pull request by ojiry**
#### Purpose

Run tests with latest stable version.

### CODE REVIEW

**Comment by geemus** [comment]
Great idea. Perhaps we should just do `2.3` though? I think that aliases to the newest 2.3, so we would automatically get updates. What do you think?

**Comment by ojiry** [comment]
@geemus I totally agree! Updated to `2.3`.
Thanks 😄

**Comment by geemus** [comment]
Well, it was worth a shot. Seems that travis doesn't like this (and we probably need to be more specific after all). See also: https://github.com/travis-ci/travis-ci/issues/5361. Thanks for your understanding, if you could tweak it back to the specific version I will pull it in once the build passes. Thanks!

**Comment by ojiry** [comment]
Oops! I returned to `2.3.3`.
FYR: Adding `dist: trusty` option travis could use the` 2.3` alias.
cf. https://github.com/otaku-dev/otacop/blob/master/.travis.yml#L2

**Comment by geemus** [comment]
Cool, thanks! I'll keep the trusty option in mind, but this seems fine for the moment anyway.

**Comment by ojiry** [comment]
Thank you for merged!

**Pull request merged**
