### PR TITLE
json 1.8.2 adds ruby 2.2 support

### PR DESCRIPTION
**Pull request by jrafanie**
Excon depends on json via the rdoc dependency.  We need to add a direct
dependency on json since the rdoc dependency for json (~> 1.4) doesn't enforce 1.8.2.

See: https://github.com/flori/json/issues/229

This fixes "error: too few arguments provided to function-like macro invocation" I was seeing in the travis build failures on ruby 2.2.

Between this PR and #463, I was able to bundle and run the test suite on ruby 2.2

@geemus Please review!

### CODE REVIEW

**Comment by geemus** [comment]
Shouldn't this have fixed the 2.2 build then?

**Comment by jrafanie** [comment]
@geemus Sorry, I split up the PRs since they were separate issues so it's probably failing on the other PR's issue.

Let me change this one to build on top of #463 and so we'll get the results with both PRs.

**Comment by geemus** [comment]
No worries. I suspected that might be the case, but wasn't certain from just looking at the failure cases.

**Comment by jrafanie** [comment]
Ok @geemus, all :green_heart:, please review/merge #463 first, and then this PR

**Comment by geemus** [comment]
Awesome, thanks for helping get to the bottom of that!

**Pull request merged**
