### PR TITLE
Persistent auth

### LINKED ISSUE #588: Individual requests should allow new/distinct user/pass
Right now the basic auth header is only generated on connection creation (rather than being updated on per-request), as a work around you can explicitly supply the header, but having this just work would be better.

### PR DESCRIPTION
**Pull request by geemus**
closes #588 

builds on/supersedes #593

### CODE REVIEW

**Comment by cyberdelia** [comment]
Lovely 👍

**Comment by shale-stripe** [comment]
Oh wow! This fixed a bug I ran into on Excon 0.49.0:

```ruby
require 'excon'
headers = {'Accept' => 'application/json'}
Excon.new('https://username:password@website.com/', headers: headers)
broken = (headers == {"Accept"=>"application/json", "Authorization"=>"Basic dXNlcm5hbWU6cGFzc3dvcmQ="})
puts "Excon::#{Excon::VERSION}: Broken? #{broken}"
```

**Comment by shalecraig** [comment]
Oh wow! This fixed a bug I ran into on Excon 0.49.0:

```ruby
require 'excon'
headers = {'Accept' => 'application/json'}
Excon.new('https://username:password@website.com/', headers: headers)
broken = (headers == {"Accept"=>"application/json", "Authorization"=>"Basic dXNlcm5hbWU6cGFzc3dvcmQ="})
puts "Excon::#{Excon::VERSION}: Broken? #{broken}"
```

**Comment by geemus** [comment]
@shalecraig awesome, glad to hear it.

**Pull request merged**
